Fixes

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -84,14 +84,14 @@ jobs:
           RETRIES=3
           while (( RETRIES-- > 0 )); do
             poetry install ${{ matrix.poetry-options }}
-            if [[ $? == 0 ]]; then
+            RESULT=$?
+            if [[ "$RESULT" == 0 ]]; then
               echo "Poetry installation succeeded."
-              exit 0
+              break
             fi
-            echo "Poetry install failed; $RETRIES tries remaining."
+            echo "Poetry installation failed; $RETRIES tries remaining."
           done
-          echo "Failed 3 times."
-          exit 1
+          exit "$RESULT"
       - name: Install yolox
         # Yolox cannot be installed with poetry and only seems to work with python <= 3.10
         if: ${{ matrix.poetry-options != '' && matrix.python-version == '3.9' && startsWith(matrix.os, 'ubuntu') }}
